### ISSUE TITLE
Instructions are incomplete

### ISSUE THREAD

**Issue by spease** [Dushistov/rust_swig#110]
Hi,
First of all, thanks for writing this crate. It's quite ambitious.

I was trying to get this working with a project at work, and was running into a series of issues.

First, the instructions don't specify that you need to set up a build script. I started out using the one from the C++ tests folder.

Second, there's a lot of issues I encountered with cargo hanging when I had Sublime open (running RLS, linter, ...). This might be a separate issue.

Third, even after closing Sublime and creating the build script, and reconfiguring lib.rs to lib.rs.in, I still can't get it to build as it seems to be looking for rust_str.h

`error: Can not put/generate foreign lang helpers: update of c++\rust_interface\rust_str.h failed: the system cannot find the path specified. (os error 3)`

I'm not sure what the proper way is to get past this error. It looks like I might be able to just copy the file over, but that seems rather inelegant and undesirable as my local copy would eventually fall out of sync with the library copy...

Thanks!

**Comment by spease** [comment]
Sorry, I don’t think I understand. You say they’re bundled with it, but I have to specify a path in build.rs. How do I specify a path to the resources? Is there an example somewhere?

**Comment by Dushistov** [comment]
>You say they’re bundled with it, but I have to specify a path in build.rs.
>How do I specify a path to the resources? Is there an example somewhere?

You don't need to specify a path to the resource.
You actually should not care about `rust_str.h` at all.
I mean something wrong with output, not with input.

I mean that message: 
> error: Can not put/generate foreign lang helpers: update of c++\rust_interface\rust_str.h failed: the system cannot find the path specified. (os error 3)

tells you that something is wrong with "c++\rust_interface" directory,
it doesn't exist, or you use the wrong slash character (`\` instead of `/`),
or this path is not relative to the root of the crate.

I attached a minimal example of a crate that works for me (`cargo build`).
Does it work for you?

[foo.zip](https://github.com/Dushistov/rust_swig/files/2097887/foo.zip)

**Comment by Dushistov** [comment]
There is now detailed documentation: https://dushistov.github.io/rust_swig/ ,
plus error message about not created directory I made more clear.

**Comment by spease** [comment]
Awesome, thank you :)
