### ISSUE TITLE
class has methods, but no constructor

### ISSUE THREAD

**Issue by spease** [Dushistov/rust_swig#125]
`error: namespace rust, class XYZ: has methods but no constructor`

In this case, this is what I actually want to have happen - make it so the Rust code can create a class, but not the C++ code. Is this disabled because it's impossible, or is there some way to allow this?

**Comment by spease** [comment]
Looks like this might be a duplicate of #117

**Comment by Dushistov** [comment]
In your case may be private constructor helps:
```Rust
foreigner_class!(class TestResult {
    self_type TestResult;
    private constructor TestResult::default() -> TestResult;
  ...
});
```



>  Is this disabled because it's impossible, or is there some way to allow this?

it is disabled because of it is possible to do things like this:

```Rust
foreigner_class!(class Control {
    self_type Control;
    constructor control_new() -> Rc<RefCell<Control>>;
    method Control::set(&mut self, item: ControlItem, is_ok: bool);
...
```

So rust_swig need to know type to use for method call (**self_type**), plus what **type** constructor
return (**self_type** may be not equal to **type**), plus I do not want have heuristics that generate dummy private constructor in C++/Java or not, I want to user decide about what API he/she want to provide.
But for use-cases when "class" created by some other class I suppose I need some kind of simplification (#117),
at now you have to write:

```Rust
fn dummy_constructor() -> Foo {
   unreachable!();
}

foreigner_class!(class Foo {
    self_type Foo;
    private constructor dummy_constructor() -> Foo;
});
```
