### ISSUE TITLE
"static" methods in interface/trait

### ISSUE THREAD

**Issue by rubdos** [Dushistov/rust_swig#144]
suppose

```rust
trait Foo {
    fn bar() where Self: Sized;
}

foreign_interface! (interface FooBar {
    self_type Foo;
    bar = Foo::bar();
})
```

This crashes at compile time:

at [macroslib/src/java_jni/mod.rs:218](https://github.com/Dushistov/rust_swig/blob/4b2d0bb606bb74d4ca4093cb4dcab6339ab4bda9/macroslib/src/java_jni/mod.rs#L218):

    thread 'main' panicked at 'attempt to subtract with overflow', /home/rsmet/.cargo/registry/src/github.com-1ecc6299db9ec823/rust_swig-0.1.5/src/java_jni/mod.rs:215:67

I gave the code a quick look, and it seems to assume no "static" (is that the Rusty term?) trait methods.

They currently don't make too much sense to bind to Java though, since we can only pass them through `Box`es (instead of genericly/`impl Trait`), but it might make sense in the future.

**Comment by Dushistov** [comment]
In fact `foreign_interface!` is the way to call from `Rust` code written with not Rust language (foreign in terms of `rust_siwg`), in your case it is the way to call Java code from Rust code.
It is not the way to export `trait` to `Java`, it is the way to create callback (May be `foreign_inteface!` is not perfect name). 

So not all Rust `trait` is possible to map to `foreign_interface!`, because of not all Rust `trait` is possible to use for callbacks.

And I missed in parser the check that method contains `&self` as the first argument, I will fix this.
