### ISSUE TITLE
Support for Vec<i8> in JNI

### ISSUE THREAD

**Issue by coltfred** [Dushistov/rust_swig#159]
I was trying to write a method that takes a `Vec<i8>`, but I get an error about `Do not know conversation from foreign to such rust type 'Vec < i8 >'''`. I believe this is because the only values that can be inside a Vec (and be passed) are values that implement `SwigForeignClass`. I see that I can use a slice `&[i8]`. Is there a reason Vec isn't supported? I don't _need_ it, but curiousity and a desire to understand are propelling me forward.

**Comment by Dushistov** [comment]
@coltfred , sorry for delay, I missed somehow this issue.

> believe this is because the only values that can be inside a Vec (and be passed) are values that > implement SwigForeignClass

Not exactly, yes now there is only rule to convert `Vec<T> where T: SwigForeignClass`,
but this is because of there are predefined set of rules how convert "foreign" types from/into Rust types,
for JNI you can  see these rules here: https://github.com/Dushistov/rust_swig/blob/master/macroslib/src/java_jni/jni-include.rs

With https://docs.rs/rust_swig/0.2.0/rust_swig/struct.Generator.html#method.merge_type_map you can rewrite/extend this rules in your `build.rs`.

The rule for `Vec<i8>` as input type was simply not implemented.

> Is there a reason `Vec<i8>` isn't supported?

Because it is not clear the proper "foreign" type for this.
Should Rust `fn f(_: Vec<i8>)` have Java `public void f(byte []arg)` counterpart,
or `public void f(RustVecI8 arg)`, where `RustVecI8` Java class that has `Vec<i8>` as backend.
Both cases has advantages and disadvantages and who win depend on application.

**Comment by coltfred** [comment]
Closing this, as the question was answered and it's clear that it was ambiguous.
