### ISSUE TITLE
error: Do not know conversation from Java type to such rust type 'Vec < Foo >'

### ISSUE THREAD

**Issue by arrtchiu** [Dushistov/rust_swig#270]
Sorry for all the questions, I really appreciate your help - let's discuss if you'd like me to contribute financially!

For some reason, I can return `Vec<Foo>`s from methods but not accept them as params. References and arrays also have the same issue.

```
--- stderr
error in android bindings: src/ffi_glue.rs.in
parsing of android bindings: src/ffi_glue.rs.in failed
error: Do not know conversation from Java type to such rust type 'Vec < Foo >'
	fn TestContainers::set_struct_vec(&mut self, _: Vec<Foo>);
                                                 ^^^
```

I basically copied the code from the tests:

```rust
#[derive(Clone, Default)]
pub struct Foo {
	u32: bar,
}

#[derive(Default)]
pub struct TestContainers {
	struct_vec: Vec<Foo>,
}

impl TestContainers {
	fn set_struct_vec(&mut self, v: Vec<Foo>) {
		self.struct_vec = v;
	}
}

foreign_class!(class Foo {
	self_type Foo;
	constructor Foo::default() -> Foo;
});

foreign_class!(class TestContainers {
	self_type TestContainers;
	constructor TestContainers::default() -> TestContainers;
	fn TestContainers::set_struct_vec(&mut self, _: Vec<Foo>);
});
```

**Comment by Dushistov** [comment]
> For some reason, I can return Vec<Foo>s from methods but not accept them as params. References > and arrays also have the same issue.

All type conversation rules is described via Domain specific language,
that looks like Rust macroses.

Corresponding to your problem rule you can find here:

https://github.com/Dushistov/rust_swig/blob/84846c680c84981188025ac641dfa30e4002bd1d/macroslib/src/java_jni/jni-include.rs#L470

As you see to "trigger" this rule your type should implement `Clone`,
`rust_swig` doesn't parse your real Rust code, so you should point rust_swig about Clone implementation via:

```Rust
foreign_class!(
#[derive(Clone)]
class Foo {
```

> Sorry for all the questions
> you'd like me to contribute financially!

I am more interesting in code contribution and testing.
So contribution via questions is not bad, because of it real usage in other words testing.

**Comment by arrtchiu** [comment]
Thanks! Adding that derive inside the `foreign_class!` did the trick.
Is something bad possible if I mismatch them?

**Comment by Dushistov** [comment]
> Is something bad possible if I mismatch them?

No, rust_swig generates normal Rust code, so you got compilation error about
generated code if something goes wrong.
