### ISSUE TITLE
0.5 release schedule?

### ISSUE THREAD

**Issue by clintfred** [Dushistov/rust_swig#286]
@Dushistov Do you have any thoughts on when 0.5 will release or what is needed to hit that milestone? I'm just trying to figure out if it would be better to depend on the 0.4 release or HEAD. 

Are 0.4 and what's on master mostly compatible at this point?

Thanks for all your work on this project!

**Comment by Dushistov** [comment]
@clintfred 

There is no fixed schedule. There is only list of features/bugs required for release:

https://github.com/Dushistov/rust_swig/milestone/7

The hard requirements is closing: #288 and #287,
other issues are optional for release.

> Are 0.4 and what's on master mostly compatible at this point?

I try to mark breaking compatibility commits with "breaking changes" keywords,
and there are no such commits since 0.4 tag.

**Comment by clintfred** [comment]
Thanks for the clarifications. Closing.
