### ISSUE TITLE
Structs with Option<Duration> fail to generate valid C++ code.

### ISSUE THREAD

**Issue by coltfred** [Dushistov/rust_swig#305]
We've been using rust_swig to generate the java (and recently android) bindings, but it appears that Option<Duration> in a struct does not generate valid C++ code. I'll include the error here, but I've also attached the headers just in case you want to see it.

```
/usr/include/c++/9.3.0/optional: In instantiation of ‘union std::_Optional_payload_base<const sdk::DurationWrapper<true>&>::_Storage<const sdk::DurationWrapper<true>&, true>’:
/usr/include/c++/9.3.0/optional:239:30:   required from ‘struct std::_Optional_payload_base<const sdk::DurationWrapper<true>&>
’
/usr/include/c++/9.3.0/optional:353:12:   required from ‘struct std::_Optional_payload<const sdk::DurationWrapper<true>&, true, false, false>’
/usr/include/c++/9.3.0/optional:628:30:   required from ‘struct std::_Optional_base<const sdk::DurationWrapper<true>&, true, true>’
/usr/include/c++/9.3.0/optional:656:11:   required from ‘class std::optional<const sdk::DurationWrapper<true>&>’
/home/colt/src/coltfred/ironoxide-java/cpp/test/../generated/sdk/IronOxideConfig.hpp:77:5:   required from here
/usr/include/c++/9.3.0/optional:212:15: error: non-static data member ‘std::_Optional_payload_base<const sdk::DurationWrapper<true>&>::_Storage<const sdk::DurationWrapper<true>&, true>::_M_value’ in a union may not have reference type ‘const sdk::DurationWrapper<true>&’
  212 |           _Up _M_value;
      |               ^~~~~~~~
/usr/include/c++/9.3.0/optional: In instantiation of ‘class std::optional<const sdk::DurationWrapper<true>&>’:
/home/colt/src/coltfred/ironoxide-java/cpp/test/../generated/sdk/IronOxideConfig.hpp:77:5:   required from here
/usr/include/c++/9.3.0/optional:672:21: error: static assertion failed
  672 |       static_assert(!is_reference_v<_Tp>);
      |                     ^~~~~~~~~~~~~~~~~~~~
/usr/include/c++/9.3.0/optional:888:7: error: forming pointer to reference type ‘const sdk::DurationWrapper<true>&’
  888 |       operator->() const
      |       ^~~~~~~~
/usr/include/c++/9.3.0/optional:893:7: error: forming pointer to reference type ‘const sdk::DurationWrapper<true>&’
  893 |       operator->()
      |       ^~~~~~~~
make[2]: *** [CMakeFiles/cpp-tests.dir/build.make:80: CMakeFiles/cpp-tests.dir/test.cpp.o] Error 1

```
[headers.tar.gz](https://github.com/Dushistov/rust_swig/files/4446966/headers.tar.gz)

The test is also checked in to our OSS repository, though it's not super simple to build, yet. I think this will give you enough information to figure out if it's my fault or if the code generation just can't handle this case right now.

https://github.com/IronCoreLabs/ironoxide-java/pull/109/

**Comment by Dushistov** [comment]
The right now fix will be changing 
`Option<&Duration>` to `Option<Duration>`,
it is `Copy` type any way, so it should be faster by passing it by value.

On your site I will convert it into `std::chrono::duration<>` instead of boxing.

But this is obviously bug, rust_swig should be minimum emit error here,
maximum handle reference inside `Option`.

**Comment by coltfred** [comment]
@Dushistov Any thoughts on what we could do for generation of C++ code when the rust type is Option<&T>? I don't write much C++, just trying to get bindings for others.

We have this in many cases, so it's a real sticking point for using rust_swig for C++ generation.

**Comment by Dushistov** [comment]
@coltfred 

I dig into this:
https://stackoverflow.com/questions/40382838/why-gcc-rejects-stdoptional-for-references
https://stackoverflow.com/questions/26858034/stdoptional-specialization-for-reference-types
https://www.fluentcpp.com/2018/10/05/pros-cons-optional-references/

so `std::option<T&>` is illegal at least for C++17, that's why compiler error.
You can use `boot::optional` instead via:
```
CppConfig::new(cpp_gen_path, "rust".into())
            .cpp_optional(CppOptional::Boost)
```
`boost::optional` works just fine with references (I checked),
but obviously your user required to have boost installed.

Another option is write specific rule to map Rust `Option<&T>` to pointer `Class *`,
something like:

**Completly not tested!**
```rust
foreign_typemap!(
    ($p:r_type) <T: SwigForeignClass> Option<&T> <= *const swig_i_type!(T) {
        implement me
    };
    ($p:f_type, unique_prefix = "/*opt*/") <= "/*opt*/* const swig_f_type!(T)" r#"
       implement me
"#;
);
```
